### ISSUE TITLE
When env is declared in wrong way, highway will hang without indicating error.

### ISSUE THREAD

**Issue by Siemian** [netguru/highway#7]
**AS IS:**
Declaring step like this:
```
bootstrap:
    default:
        - sh:
            command: "echo $VARIABLE"
```
instead of 
```
bootstrap:
    default:
        - sh:
            command: "echo $(VARIABLE)"
```
will cause Highway to hang on:
```
--- Compiling the configuration file...
```
**TO BE:**
Highway should throw error
